apiVersion: v1
kind: Service
metadata:
  name: docker-k8s-service
  namespace: docker-k8s
spec:
  type: NodePort
  selector:
    app: docker-k8s-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30007
